name: Aggiorna Campane Fonderia Mari

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: write

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Crea cartella dataset
        run: mkdir -p datasets/campanefonderiamari

      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vR1Yz4BY014lRyM7zEx75_9QZwxQCztKQaiQyIa11-e_t5k71UPiRP5Ujxl5SpMN7p3EX5i6Fj0t-p4/pub?gid=276669619&single=true&output=csv'
          downloaded_filename: datasets/campanefonderiamari/campane.csv
